import 'package:flutter/material.dart';

// ── Model classes ─────────────────────────────────────────────────────────────

class MCUFamily {
  final String name;
  final IconData icon;
  final Color accent;
  final List<String> boards;
  const MCUFamily(this.name, this.icon, this.accent, this.boards);
}

class PinRow {
  final String pin;
  final String type;
  final String functions;
  final Color color;
  const PinRow(this.pin, this.type, this.functions, this.color);
}

// ── Color constants ───────────────────────────────────────────────────────────

const cDigital = Color(0xFF00D4FF);
const cAnalog  = Color(0xFFFFD166);
const cPWM     = Color(0xFF7B2FFF);
const cUART    = Color(0xFF06D6A0);
const cI2C     = Color(0xFFFFB347);
const cSPI     = Color(0xFF00FFB3);
const cPower   = Color(0xFFFF4D6D);
const cGND     = Color(0xFF888888);
const cSpecial = Color(0xFFFF8C42);

// ── MCU Families ─────────────────────────────────────────────────────────────

const mcuFamilies = [
  MCUFamily('ESP32', Icons.memory_rounded, Color(0xFF00D4FF), [
    'WROOM-32',  'WROOM-32D',   'WROOM-32U',
    'WROVER',    'WROVER-B',    'WROVER-E',
    'ESP32-S2',  'S2 Mini',     'S2-Saola-1',
    'ESP32-S3',  'S3-WROOM-1',  'S3 DevKitC-1',
    'ESP32-C3',  'C3 Mini',     'C3 SuperMini',
    'ESP32-C6',  'ESP32-H2',
    'DevKitC-V4','NodeMCU-32S', 'LOLIN D32',
    'LOLIN D32 Pro','TTGO T-Display','TTGO T7',
    'M5Stack Basic','M5Stack Core2','Adafruit HUZZAH32','SparkFun Thing Plus',
  ]),
  MCUFamily('Arduino', Icons.developer_board_rounded, Color(0xFF06D6A0), [
    'Uno R3',         'Uno R4 Minima',  'Uno R4 WiFi',
    'Mega 2560',      'Mega ADK',
    'Nano',           'Nano Every',     'Nano 33 IoT',
    'Nano 33 BLE',    'Nano 33 BLE Sense','Nano ESP32',
    'Due',            'Leonardo',       'Micro',
    'Pro Mini 3.3V',  'Pro Mini 5V',    'Pro Micro',
    'MKR WiFi 1010',  'MKR Zero',       'MKR GSM 1400',
    'MKR WAN 1300',   'Portenta H7',    'Zero',
    'Giga R1 WiFi',   'Nicla Sense ME',
  ]),
  MCUFamily('Raspberry Pi', Icons.computer_rounded, Color(0xFFFF4D6D), [
    'Pi 5 (4GB)',     'Pi 5 (8GB)',
    'Pi 4 Model B',   'Pi 3 Model B+',  'Pi 3 Model B',
    'Pi 3 Model A+',  'Pi 2 Model B',   'Pi 1 Model B+',
    'Pi Zero 2W',     'Pi Zero W',      'Pi Zero',
    'Pico 2W',        'Pico 2',         'Pico W',   'Pico',
    'Pi 400',         'CM4',
  ]),
  MCUFamily('STM32', Icons.settings_input_component_rounded, Color(0xFF7B2FFF), [
    'Blue Pill (F103C8)',  'Black Pill (F401)',  'Black Pill (F411)',
    'Nucleo-F103RB',       'Nucleo-F401RE',      'Nucleo-F411RE',
    'Nucleo-F446RE',       'Nucleo-F767ZI',      'Nucleo-H743ZI',
    'STM32F4-Discovery',   'STM32F0-Discovery',
    'Nucleo-G431',         'Nucleo-WB55 (BLE)',  'Nucleo-WL55 (LoRa)',
    'WeAct F401',          'WeAct F411',          'Maple Mini',
  ]),
];

// ── Alias map: board → pin-layout key ────────────────────────────────────────

const pinLayoutKey = <String, String>{
  // ESP32 classic (WROOM-32 base)
  'WROOM-32D':         'WROOM-32',
  'WROOM-32U':         'WROOM-32',
  'DevKitC-V4':        'WROOM-32',
  'NodeMCU-32S':       'WROOM-32',
  'LOLIN D32':         'WROOM-32',
  'Adafruit HUZZAH32': 'WROOM-32',
  'SparkFun Thing Plus':'WROOM-32',
  'TTGO T7':           'WROOM-32',
  // ESP32 WROVER (PSRAM on GPIO16/17)
  'WROVER-B':          'WROVER',
  'WROVER-E':          'WROVER',
  'LOLIN D32 Pro':     'WROVER',
  'M5Stack Core2':     'WROVER',
  // ESP32-S2 variants
  'S2 Mini':           'ESP32-S2',
  'S2-Saola-1':        'ESP32-S2',
  // ESP32-S3 variants
  'S3-WROOM-1':        'ESP32-S3',
  'S3 DevKitC-1':      'ESP32-S3',
  'M5Stack Basic':     'ESP32-S3',
  // ESP32-C3 variants
  'C3 Mini':           'ESP32-C3',
  'C3 SuperMini':      'ESP32-C3',
  // TTGO T-Display = WROOM-32 with display
  'TTGO T-Display':    'TTGO T-Display',
  // Arduino families
  'Uno R4 Minima':     'Uno R3',
  'Uno R4 WiFi':       'Uno R3',
  'Zero':              'Uno R3',
  'Mega ADK':          'Mega 2560',
  'Nano Every':        'Nano',
  'Nano 33 BLE Sense': 'Nano 33 BLE',
  'Pro Mini 5V':       'Pro Mini 3.3V',
  'Pro Micro':         'Pro Mini 3.3V',
  'MKR Zero':          'MKR WiFi 1010',
  'MKR GSM 1400':      'MKR WiFi 1010',
  'MKR WAN 1300':      'MKR WiFi 1010',
  // Raspberry Pi 40-pin header family
  'Pi 5 (4GB)':        'Pi 40-pin',
  'Pi 5 (8GB)':        'Pi 40-pin',
  'Pi 4 Model B':      'Pi 40-pin',
  'Pi 3 Model B+':     'Pi 40-pin',
  'Pi 3 Model B':      'Pi 40-pin',
  'Pi 3 Model A+':     'Pi 40-pin',
  'Pi 2 Model B':      'Pi 40-pin',
  'Pi 1 Model B+':     'Pi 40-pin',
  'Pi Zero 2W':        'Pi 40-pin',
  'Pi Zero W':         'Pi 40-pin',
  'Pi Zero':           'Pi 40-pin',
  'Pi 400':            'Pi 40-pin',
  'CM4':               'Pi 40-pin',
  'Pico W':            'Pico',
  'Pico 2':            'Pico 2W',
  // STM32
  'Nucleo-F103RB':     'Nucleo-64',
  'Nucleo-F401RE':     'Nucleo-64',
  'Nucleo-F411RE':     'Nucleo-64',
  'Nucleo-F446RE':     'Nucleo-64',
  'Nucleo-F767ZI':     'Nucleo-144',
  'Nucleo-H743ZI':     'Nucleo-144',
  'Nucleo-G431':       'Nucleo-64',
  'WeAct F401':        'Black Pill (F401)',
  'WeAct F411':        'Black Pill (F411)',
  'STM32F0-Discovery': 'STM32F4-Discovery',
};

String resolveKey(String model) => pinLayoutKey[model] ?? model;

// ── Pin layouts ───────────────────────────────────────────────────────────────

final pinLayouts = <String, List<PinRow>>{

  // ══ ESP32 WROOM-32 ════════════════════════════════════════════════════════
  'WROOM-32': [
    PinRow('GPIO 0',  'Digital', 'Boot mode · ADC2_CH1 · Touch 1',             cDigital),
    PinRow('GPIO 1',  'UART',    'TX0 — Serial monitor',                        cUART),
    PinRow('GPIO 2',  'Digital', 'Output only · PWM · ADC2_CH2 · Touch 2',     cDigital),
    PinRow('GPIO 3',  'UART',    'RX0 — Serial monitor',                        cUART),
    PinRow('GPIO 4',  'Digital', 'Input/Output · ADC2_CH0 · Touch 0',          cDigital),
    PinRow('GPIO 5',  'SPI',     'VSPI CS0 · PWM',                              cSPI),
    PinRow('GPIO 12', 'Digital', 'PWM · ADC2_CH5 · Touch 5 · JTAG TDI',       cPWM),
    PinRow('GPIO 13', 'Digital', 'PWM · ADC2_CH4 · Touch 4 · JTAG TCK',       cPWM),
    PinRow('GPIO 14', 'Digital', 'PWM · ADC2_CH6 · Touch 6 · JTAG TMS',       cPWM),
    PinRow('GPIO 15', 'SPI',     'VSPI CS · JTAG TDO',                         cSPI),
    PinRow('GPIO 16', 'Digital', 'Input/Output (avoid if WROVER)',              cDigital),
    PinRow('GPIO 17', 'Digital', 'Input/Output (avoid if WROVER)',              cDigital),
    PinRow('GPIO 18', 'SPI',     'VSPI CLK',                                    cSPI),
    PinRow('GPIO 19', 'SPI',     'VSPI MISO',                                   cSPI),
    PinRow('GPIO 21', 'I2C',     'I2C SDA (default)',                           cI2C),
    PinRow('GPIO 22', 'I2C',     'I2C SCL (default)',                           cI2C),
    PinRow('GPIO 23', 'SPI',     'VSPI MOSI',                                   cSPI),
    PinRow('GPIO 25', 'Analog',  'DAC1 · ADC2_CH8',                            cAnalog),
    PinRow('GPIO 26', 'Analog',  'DAC2 · ADC2_CH9',                            cAnalog),
    PinRow('GPIO 27', 'Digital', 'PWM · ADC2_CH7 · Touch 7',                   cPWM),
    PinRow('GPIO 32', 'Analog',  'ADC1_CH4 · Touch 9 · 32kHz XTAL',           cAnalog),
    PinRow('GPIO 33', 'Analog',  'ADC1_CH5 · Touch 8 · 32kHz XTAL',           cAnalog),
    PinRow('GPIO 34', 'Analog',  'ADC1_CH6 · Input only',                      cAnalog),
    PinRow('GPIO 35', 'Analog',  'ADC1_CH7 · Input only',                      cAnalog),
    PinRow('GPIO 36', 'Analog',  'ADC1_CH0 · Input only (VP)',                 cAnalog),
    PinRow('GPIO 39', 'Analog',  'ADC1_CH3 · Input only (VN)',                 cAnalog),
    PinRow('EN',      'Special', 'Chip enable · Reset (active LOW)',            cSpecial),
    PinRow('3V3',     'Power',   '3.3 V regulated output (max 600 mA)',        cPower),
    PinRow('GND',     'GND',     'Ground reference',                            cGND),
    PinRow('VIN',     'Power',   '5 V input via USB / barrel jack',             cPower),
  ],

  // ══ ESP32 WROVER (GPIO16/17 tied to PSRAM) ════════════════════════════════
  'WROVER': [
    PinRow('GPIO 0',  'Digital', 'Boot mode · ADC2_CH1 · Touch 1',             cDigital),
    PinRow('GPIO 2',  'Digital', 'Output · PWM · ADC2_CH2',                    cDigital),
    PinRow('GPIO 4',  'Digital', 'Input/Output · ADC2_CH0',                    cDigital),
    PinRow('GPIO 5',  'SPI',     'VSPI CS0',                                    cSPI),
    PinRow('GPIO 12', 'Digital', 'PWM · ADC2_CH5 · JTAG TDI',                 cPWM),
    PinRow('GPIO 13', 'Digital', 'PWM · ADC2_CH4 · JTAG TCK',                 cPWM),
    PinRow('GPIO 14', 'Digital', 'PWM · ADC2_CH6 · JTAG TMS',                 cPWM),
    PinRow('GPIO 15', 'SPI',     'VSPI CS · JTAG TDO',                         cSPI),
    PinRow('GPIO 16', 'Special', '⚠ PSRAM — do NOT use externally',            cSpecial),
    PinRow('GPIO 17', 'Special', '⚠ PSRAM — do NOT use externally',            cSpecial),
    PinRow('GPIO 18', 'SPI',     'VSPI CLK',                                    cSPI),
    PinRow('GPIO 19', 'SPI',     'VSPI MISO',                                   cSPI),
    PinRow('GPIO 21', 'I2C',     'I2C SDA',                                     cI2C),
    PinRow('GPIO 22', 'I2C',     'I2C SCL',                                     cI2C),
    PinRow('GPIO 23', 'SPI',     'VSPI MOSI',                                   cSPI),
    PinRow('GPIO 25', 'Analog',  'DAC1 · ADC2_CH8',                            cAnalog),
    PinRow('GPIO 26', 'Analog',  'DAC2 · ADC2_CH9',                            cAnalog),
    PinRow('GPIO 32', 'Analog',  'ADC1_CH4 · Touch 9',                         cAnalog),
    PinRow('GPIO 33', 'Analog',  'ADC1_CH5 · Touch 8',                         cAnalog),
    PinRow('GPIO 34', 'Analog',  'ADC1_CH6 · Input only',                      cAnalog),
    PinRow('GPIO 35', 'Analog',  'ADC1_CH7 · Input only',                      cAnalog),
    PinRow('GPIO 36', 'Analog',  'VP — Input only',                             cAnalog),
    PinRow('GPIO 39', 'Analog',  'VN — Input only',                             cAnalog),
    PinRow('3V3',     'Power',   '3.3 V output',                                cPower),
    PinRow('GND',     'GND',     'Ground',                                       cGND),
    PinRow('VIN',     'Power',   '5 V input',                                   cPower),
  ],

  // ══ ESP32-S2 ═════════════════════════════════════════════════════════════
  'ESP32-S2': [
    PinRow('GPIO 1',  'Analog',  'ADC1_CH0 · Touch 1',                         cAnalog),
    PinRow('GPIO 2',  'Analog',  'ADC1_CH1 · Touch 2',                         cAnalog),
    PinRow('GPIO 3',  'Analog',  'ADC1_CH2 · Touch 3',                         cAnalog),
    PinRow('GPIO 4',  'Analog',  'ADC1_CH3 · Touch 4 · DAC1',                 cAnalog),
    PinRow('GPIO 5',  'Analog',  'ADC1_CH4 · Touch 5 · DAC2',                 cAnalog),
    PinRow('GPIO 6',  'Analog',  'ADC1_CH5 · Touch 6',                         cAnalog),
    PinRow('GPIO 7',  'Digital', 'PWM · Touch 7',                               cDigital),
    PinRow('GPIO 8',  'Digital', 'PWM · Touch 8',                               cDigital),
    PinRow('GPIO 9',  'Digital', 'PWM · Touch 9',                               cDigital),
    PinRow('GPIO 10', 'Digital', 'PWM · Touch 10',                              cDigital),
    PinRow('GPIO 11', 'Digital', 'PWM · Touch 11',                              cDigital),
    PinRow('GPIO 12', 'Digital', 'PWM · Touch 12',                              cDigital),
    PinRow('GPIO 13', 'Digital', 'Touch 13',                                    cDigital),
    PinRow('GPIO 14', 'Digital', 'Touch 14',                                    cDigital),
    PinRow('GPIO 33', 'SPI',     'FSPI CLK',                                    cSPI),
    PinRow('GPIO 34', 'SPI',     'FSPI MISO',                                   cSPI),
    PinRow('GPIO 35', 'SPI',     'FSPI MOSI',                                   cSPI),
    PinRow('GPIO 36', 'SPI',     'FSPI CS0',                                    cSPI),
    PinRow('GPIO 37', 'SPI',     'FSPI CS1',                                    cSPI),
    PinRow('GPIO 39', 'I2C',     'I2C SDA (default)',                           cI2C),
    PinRow('GPIO 40', 'I2C',     'I2C SCL (default)',                           cI2C),
    PinRow('GPIO 43', 'UART',    'UART0 TX',                                    cUART),
    PinRow('GPIO 44', 'UART',    'UART0 RX',                                    cUART),
    PinRow('GPIO 45', 'Special', 'VDD_SPI strapping',                           cSpecial),
    PinRow('GPIO 46', 'Special', 'Input only · Strapping',                      cSpecial),
    PinRow('3V3',     'Power',   '3.3 V output',                                cPower),
    PinRow('GND',     'GND',     'Ground',                                       cGND),
  ],

  // ══ ESP32-S3 ═════════════════════════════════════════════════════════════
  'ESP32-S3': [
    PinRow('GPIO 1',  'Analog',  'ADC1_CH0 · Touch 1',                         cAnalog),
    PinRow('GPIO 2',  'Analog',  'ADC1_CH1 · Touch 2',                         cAnalog),
    PinRow('GPIO 3',  'Analog',  'ADC1_CH2 · Touch 3',                         cAnalog),
    PinRow('GPIO 4',  'Analog',  'ADC1_CH3 · Touch 4',                         cAnalog),
    PinRow('GPIO 5',  'Digital', 'PWM · Touch 5',                               cDigital),
    PinRow('GPIO 6',  'Digital', 'PWM · Touch 6',                               cDigital),
    PinRow('GPIO 7',  'Digital', 'PWM · Touch 7',                               cDigital),
    PinRow('GPIO 8',  'Digital', 'PWM · Touch 8',                               cDigital),
    PinRow('GPIO 9',  'Digital', 'PWM · Touch 9',                               cDigital),
    PinRow('GPIO 10', 'Digital', 'PWM · Touch 10',                              cDigital),
    PinRow('GPIO 11', 'Digital', 'PWM · Touch 11',                              cDigital),
    PinRow('GPIO 12', 'Digital', 'PWM · Touch 12',                              cDigital),
    PinRow('GPIO 13', 'Digital', 'Touch 13',                                    cDigital),
    PinRow('GPIO 14', 'Digital', 'Touch 14',                                    cDigital),
    PinRow('GPIO 15', 'SPI',     'FSPI CS0',                                    cSPI),
    PinRow('GPIO 16', 'SPI',     'FSPI CLK',                                    cSPI),
    PinRow('GPIO 17', 'SPI',     'FSPI MOSI',                                   cSPI),
    PinRow('GPIO 18', 'SPI',     'FSPI MISO',                                   cSPI),
    PinRow('GPIO 19', 'Special', 'USB D− (native USB)',                         cSpecial),
    PinRow('GPIO 20', 'Special', 'USB D+ (native USB)',                         cSpecial),
    PinRow('GPIO 35', 'I2C',     'I2C SDA (default)',                           cI2C),
    PinRow('GPIO 36', 'I2C',     'I2C SCL (default)',                           cI2C),
    PinRow('GPIO 43', 'UART',    'UART0 TX',                                    cUART),
    PinRow('GPIO 44', 'UART',    'UART0 RX',                                    cUART),
    PinRow('GPIO 45', 'Special', 'Strapping — JTAG/USB select',                 cSpecial),
    PinRow('GPIO 46', 'Special', 'Strapping — ROM log',                         cSpecial),
    PinRow('GPIO 47', 'Digital', 'Input/Output',                                cDigital),
    PinRow('GPIO 48', 'Digital', 'Input/Output',                                cDigital),
    PinRow('3V3',     'Power',   '3.3 V output',                                cPower),
    PinRow('GND',     'GND',     'Ground',                                       cGND),
  ],

  // ══ ESP32-C3 (RISC-V) ═════════════════════════════════════════════════════
  'ESP32-C3': [
    PinRow('GPIO 0',  'Analog',  'ADC1_CH0 · Touch 0',                         cAnalog),
    PinRow('GPIO 1',  'Analog',  'ADC1_CH1 · Touch 1',                         cAnalog),
    PinRow('GPIO 2',  'Analog',  'ADC1_CH2 · Strapping',                       cAnalog),
    PinRow('GPIO 3',  'Analog',  'ADC1_CH3',                                    cAnalog),
    PinRow('GPIO 4',  'Analog',  'ADC1_CH4 · MTMS',                            cAnalog),
    PinRow('GPIO 5',  'Analog',  'ADC2_CH0 · MTDI',                            cAnalog),
    PinRow('GPIO 6',  'SPI',     'FSPI CLK / MTCK',                             cSPI),
    PinRow('GPIO 7',  'SPI',     'FSPI MOSI / MTDO',                            cSPI),
    PinRow('GPIO 8',  'Digital', 'PWM · Strapping',                             cDigital),
    PinRow('GPIO 9',  'Digital', 'PWM · Strapping · Boot mode',                 cDigital),
    PinRow('GPIO 10', 'Digital', 'PWM',                                          cDigital),
    PinRow('GPIO 18', 'Special', 'USB D−',                                       cSpecial),
    PinRow('GPIO 19', 'Special', 'USB D+',                                       cSpecial),
    PinRow('GPIO 20', 'UART',    'UART0 RX',                                    cUART),
    PinRow('GPIO 21', 'UART',    'UART0 TX',                                    cUART),
    PinRow('3V3',     'Power',   '3.3 V output',                                cPower),
    PinRow('GND',     'GND',     'Ground',                                       cGND),
  ],

  // ══ ESP32-C6 (WiFi 6 + BLE 5.3 + Zigbee) ════════════════════════════════
  'ESP32-C6': [
    PinRow('GPIO 0',  'Analog',  'ADC1_CH0 · FSPIQ',                           cAnalog),
    PinRow('GPIO 1',  'Analog',  'ADC1_CH1 · FSPICS0',                         cAnalog),
    PinRow('GPIO 2',  'Analog',  'ADC1_CH2 · FSPIWP',                          cAnalog),
    PinRow('GPIO 3',  'Analog',  'ADC1_CH3 · FSPIHD',                          cAnalog),
    PinRow('GPIO 4',  'SPI',     'MTMS · FSPICLK',                              cSPI),
    PinRow('GPIO 5',  'SPI',     'MTDI · FSPID',                                cSPI),
    PinRow('GPIO 6',  'Digital', 'MTCK',                                        cDigital),
    PinRow('GPIO 7',  'Digital', 'MTDO',                                        cDigital),
    PinRow('GPIO 8',  'Digital', 'PWM · Strapping',                             cDigital),
    PinRow('GPIO 9',  'Digital', 'PWM · Strapping · Boot',                      cDigital),
    PinRow('GPIO 10', 'Digital', 'PWM',                                          cDigital),
    PinRow('GPIO 11', 'Digital', 'VDD_SPI strapping',                           cDigital),
    PinRow('GPIO 12', 'SPI',     'SPIHD',                                        cSPI),
    PinRow('GPIO 13', 'SPI',     'SPIWP',                                        cSPI),
    PinRow('GPIO 14', 'SPI',     'SPICLK',                                       cSPI),
    PinRow('GPIO 15', 'SPI',     'SPICS0',                                       cSPI),
    PinRow('GPIO 16', 'UART',    'UART0 TX',                                    cUART),
    PinRow('GPIO 17', 'UART',    'UART0 RX',                                    cUART),
    PinRow('GPIO 18', 'Special', 'USB D−',                                       cSpecial),
    PinRow('GPIO 19', 'Special', 'USB D+',                                       cSpecial),
    PinRow('GPIO 20', 'I2C',     'I2C SDA (default)',                           cI2C),
    PinRow('GPIO 21', 'I2C',     'I2C SCL (default)',                           cI2C),
    PinRow('GPIO 22', 'Digital', 'Input/Output',                                cDigital),
    PinRow('GPIO 23', 'Digital', 'Input/Output',                                cDigital),
    PinRow('3V3',     'Power',   '3.3 V output',                                cPower),
    PinRow('GND',     'GND',     'Ground',                                       cGND),
  ],

  // ══ ESP32-H2 (Zigbee/Thread/BLE) ═════════════════════════════════════════
  'ESP32-H2': [
    PinRow('GPIO 0',  'Analog',  'ADC1_CH0',                                    cAnalog),
    PinRow('GPIO 1',  'Analog',  'ADC1_CH1',                                    cAnalog),
    PinRow('GPIO 2',  'Analog',  'ADC1_CH2 · Strapping',                       cAnalog),
    PinRow('GPIO 3',  'Analog',  'ADC1_CH3',                                    cAnalog),
    PinRow('GPIO 4',  'Analog',  'ADC1_CH4 · MTMS',                            cAnalog),
    PinRow('GPIO 5',  'Digital', 'MTDI',                                        cDigital),
    PinRow('GPIO 8',  'Digital', 'PWM · Strapping · Boot',                      cDigital),
    PinRow('GPIO 9',  'Digital', 'PWM · Strapping',                             cDigital),
    PinRow('GPIO 10', 'Digital', 'PWM',                                          cDigital),
    PinRow('GPIO 11', 'Digital', 'Input/Output',                                cDigital),
    PinRow('GPIO 12', 'UART',    'UART0 TX',                                    cUART),
    PinRow('GPIO 13', 'UART',    'UART0 RX',                                    cUART),
    PinRow('GPIO 22', 'Special', 'USB D−',                                       cSpecial),
    PinRow('GPIO 23', 'Special', 'USB D+',                                       cSpecial),
    PinRow('GPIO 24', 'Digital', 'LP_GPIO0',                                    cDigital),
    PinRow('GPIO 25', 'Digital', 'LP_GPIO1',                                    cDigital),
    PinRow('3V3',     'Power',   '3.3 V',                                       cPower),
    PinRow('GND',     'GND',     'Ground',                                       cGND),
  ],

  // ══ TTGO T-Display (ESP32 + ST7789 1.14" 135×240) ════════════════════════
  'TTGO T-Display': [
    PinRow('GPIO 0',  'Special', 'Boot button',                                  cSpecial),
    PinRow('GPIO 2',  'Digital', 'SD card CS',                                  cDigital),
    PinRow('GPIO 4',  'Special', 'TFT backlight (PWM)',                         cSpecial),
    PinRow('GPIO 5',  'SPI',     'TFT CS',                                       cSPI),
    PinRow('GPIO 12', 'Digital', 'Input/Output',                                cDigital),
    PinRow('GPIO 13', 'Digital', 'Right button',                                cDigital),
    PinRow('GPIO 14', 'Digital', 'Left button',                                 cDigital),
    PinRow('GPIO 15', 'Digital', 'Input/Output',                                cDigital),
    PinRow('GPIO 16', 'UART',    'UART2 RX / user IO',                          cUART),
    PinRow('GPIO 17', 'UART',    'UART2 TX / user IO',                          cUART),
    PinRow('GPIO 18', 'SPI',     'TFT SCK',                                      cSPI),
    PinRow('GPIO 19', 'SPI',     'VSPI MISO (user)',                             cSPI),
    PinRow('GPIO 21', 'I2C',     'I2C SDA',                                      cI2C),
    PinRow('GPIO 22', 'I2C',     'I2C SCL',                                      cI2C),
    PinRow('GPIO 23', 'SPI',     'TFT MOSI / VSPI MOSI',                        cSPI),
    PinRow('GPIO 25', 'Analog',  'DAC1 / user IO',                              cAnalog),
    PinRow('GPIO 26', 'Analog',  'DAC2 / user IO',                              cAnalog),
    PinRow('GPIO 27', 'Special', 'TFT DC (data/cmd)',                           cSpecial),
    PinRow('GPIO 32', 'Analog',  'ADC1_CH4 / user IO',                         cAnalog),
    PinRow('GPIO 33', 'Analog',  'ADC1_CH5 / user IO',                         cAnalog),
    PinRow('GPIO 34', 'Analog',  'ADC1_CH6 · Input only',                      cAnalog),
    PinRow('GPIO 35', 'Analog',  'ADC1_CH7 · Input only',                      cAnalog),
    PinRow('GPIO 36', 'Analog',  'VP — Input only',                             cAnalog),
    PinRow('GPIO 39', 'Analog',  'VN — Input only',                             cAnalog),
    PinRow('3V3',     'Power',   '3.3 V output',                                cPower),
    PinRow('GND',     'GND',     'Ground',                                       cGND),
    PinRow('VIN',     'Power',   '5 V / LiPo (charge via USB)',                 cPower),
  ],

  // ══ ARDUINO UNO R3 ════════════════════════════════════════════════════════
  'Uno R3': [
    PinRow('D0',   'UART',    'Digital · RX Serial',                             cUART),
    PinRow('D1',   'UART',    'Digital · TX Serial',                             cUART),
    PinRow('D2',   'Digital', 'Digital I/O · External Interrupt 0',             cDigital),
    PinRow('D3',   'PWM',     'Digital · PWM · External Interrupt 1',           cPWM),
    PinRow('D4',   'Digital', 'Digital I/O',                                    cDigital),
    PinRow('D5',   'PWM',     'Digital · PWM',                                   cPWM),
    PinRow('D6',   'PWM',     'Digital · PWM',                                   cPWM),
    PinRow('D7',   'Digital', 'Digital I/O',                                    cDigital),
    PinRow('D8',   'Digital', 'Digital I/O',                                    cDigital),
    PinRow('D9',   'PWM',     'Digital · PWM',                                   cPWM),
    PinRow('D10',  'SPI',     'Digital · PWM · SPI SS',                         cSPI),
    PinRow('D11',  'SPI',     'Digital · PWM · SPI MOSI',                       cSPI),
    PinRow('D12',  'SPI',     'Digital · SPI MISO',                             cSPI),
    PinRow('D13',  'Special', 'Digital · SPI SCK · Built-in LED',               cSpecial),
    PinRow('A0',   'Analog',  'Analog Input 10-bit (0–5 V)',                    cAnalog),
    PinRow('A1',   'Analog',  'Analog Input 10-bit',                            cAnalog),
    PinRow('A2',   'Analog',  'Analog Input 10-bit',                            cAnalog),
    PinRow('A3',   'Analog',  'Analog Input 10-bit',                            cAnalog),
    PinRow('A4',   'I2C',     'Analog · I2C SDA (Wire)',                        cI2C),
    PinRow('A5',   'I2C',     'Analog · I2C SCL (Wire)',                        cI2C),
    PinRow('AREF', 'Special', 'Analog reference voltage',                       cSpecial),
    PinRow('RESET','Special', 'Reset (active LOW)',                              cSpecial),
    PinRow('5V',   'Power',   '5 V regulated output',                           cPower),
    PinRow('3.3V', 'Power',   '3.3 V output (150 mA max)',                     cPower),
    PinRow('GND',  'GND',     'Ground',                                          cGND),
    PinRow('VIN',  'Power',   'Unregulated input (7–12 V)',                     cPower),
  ],

  // ══ ARDUINO MEGA 2560 ═════════════════════════════════════════════════════
  'Mega 2560': [
    PinRow('D0',  'UART',  'RX0',                                                cUART),
    PinRow('D1',  'UART',  'TX0',                                                cUART),
    PinRow('D2',  'PWM',   'Digital · PWM · Interrupt 0',                       cPWM),
    PinRow('D3',  'PWM',   'Digital · PWM · Interrupt 1',                       cPWM),
    PinRow('D4',  'PWM',   'Digital · PWM · OC0B',                              cPWM),
    PinRow('D5',  'PWM',   'Digital · PWM · OC3A',                              cPWM),
    PinRow('D6',  'PWM',   'Digital · PWM · OC4A',                              cPWM),
    PinRow('D7',  'PWM',   'Digital · PWM · OC4B',                              cPWM),
    PinRow('D8',  'PWM',   'Digital · PWM · OC4C',                              cPWM),
    PinRow('D9',  'PWM',   'Digital · PWM · OC2B',                              cPWM),
    PinRow('D10', 'PWM',   'Digital · PWM · OC2A · SPI SS',                    cPWM),
    PinRow('D11', 'SPI',   'Digital · PWM · SPI MOSI',                          cSPI),
    PinRow('D12', 'SPI',   'Digital · SPI MISO',                                cSPI),
    PinRow('D13', 'SPI',   'Digital · SPI SCK · LED',                           cSPI),
    PinRow('D14', 'UART',  'TX3',                                                cUART),
    PinRow('D15', 'UART',  'RX3',                                                cUART),
    PinRow('D16', 'UART',  'TX2',                                                cUART),
    PinRow('D17', 'UART',  'RX2',                                                cUART),
    PinRow('D18', 'UART',  'TX1 · Interrupt 5',                                 cUART),
    PinRow('D19', 'UART',  'RX1 · Interrupt 4',                                 cUART),
    PinRow('D20', 'I2C',   'SDA · Interrupt 3',                                 cI2C),
    PinRow('D21', 'I2C',   'SCL · Interrupt 2',                                 cI2C),
    PinRow('D22–D53', 'Digital', 'General-purpose digital I/O (x32)',           cDigital),
    PinRow('A0',  'Analog','10-bit ADC (also D54)',                             cAnalog),
    PinRow('A1',  'Analog','10-bit ADC (also D55)',                             cAnalog),
    PinRow('A2',  'Analog','10-bit ADC (also D56)',                             cAnalog),
    PinRow('A3',  'Analog','10-bit ADC (also D57)',                             cAnalog),
    PinRow('A4',  'Analog','10-bit ADC (also D58)',                             cAnalog),
    PinRow('A5',  'Analog','10-bit ADC (also D59)',                             cAnalog),
    PinRow('A6–A15','Analog','Additional 10-bit ADC channels',                 cAnalog),
    PinRow('5V',  'Power', '5 V output',                                        cPower),
    PinRow('3.3V','Power', '3.3 V output',                                      cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
    PinRow('VIN', 'Power', '7–12 V input',                                      cPower),
  ],

  // ══ ARDUINO NANO ══════════════════════════════════════════════════════════
  'Nano': [
    PinRow('D0',  'UART',  'Digital · RX',                                      cUART),
    PinRow('D1',  'UART',  'Digital · TX',                                      cUART),
    PinRow('D2',  'Digital','Digital · Interrupt',                              cDigital),
    PinRow('D3',  'PWM',   'Digital · PWM · Interrupt',                         cPWM),
    PinRow('D4',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D5',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D6',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D7',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D8',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D9',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D10', 'SPI',   'Digital · PWM · SPI SS',                            cSPI),
    PinRow('D11', 'SPI',   'Digital · PWM · SPI MOSI',                         cSPI),
    PinRow('D12', 'SPI',   'Digital · SPI MISO',                                cSPI),
    PinRow('D13', 'Special','Digital · SPI SCK · LED',                          cSpecial),
    PinRow('A0',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('A1',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('A2',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('A3',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('A4',  'I2C',   'Analog · I2C SDA',                                  cI2C),
    PinRow('A5',  'I2C',   'Analog · I2C SCL',                                  cI2C),
    PinRow('A6',  'Analog','Analog Input only',                                 cAnalog),
    PinRow('A7',  'Analog','Analog Input only',                                 cAnalog),
    PinRow('5V',  'Power', '5 V output',                                        cPower),
    PinRow('3V3', 'Power', '3.3 V output',                                      cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
    PinRow('VIN', 'Power', '7–12 V input',                                      cPower),
  ],

  // ══ ARDUINO NANO 33 IOT ═══════════════════════════════════════════════════
  'Nano 33 IoT': [
    PinRow('D0',  'UART',  'RX (Serial1) — 3.3 V logic only',                  cUART),
    PinRow('D1',  'UART',  'TX (Serial1)',                                       cUART),
    PinRow('D2',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D3',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D4',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D5',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D6',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D7',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D8',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D9',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D10', 'SPI',   'SPI SS · PWM',                                      cSPI),
    PinRow('D11', 'SPI',   'SPI MOSI · PWM',                                    cSPI),
    PinRow('D12', 'SPI',   'SPI MISO',                                           cSPI),
    PinRow('D13', 'Special','SPI SCK · Built-in LED',                           cSpecial),
    PinRow('A0',  'Analog','12-bit ADC · DAC',                                  cAnalog),
    PinRow('A1',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A2',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A3',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A4',  'I2C',   'I2C SDA (Wire) · 12-bit ADC',                      cI2C),
    PinRow('A5',  'I2C',   'I2C SCL (Wire) · 12-bit ADC',                      cI2C),
    PinRow('A6',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A7',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('3V3', 'Power', '3.3 V output (⚠ 3.3 V only board)',                cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
    PinRow('VIN', 'Power', '5 V input (USB)',                                   cPower),
  ],

  // ══ ARDUINO NANO 33 BLE ═══════════════════════════════════════════════════
  'Nano 33 BLE': [
    PinRow('D0',  'UART',  'RX (Serial1) — 3.3 V only',                        cUART),
    PinRow('D1',  'UART',  'TX (Serial1)',                                       cUART),
    PinRow('D2',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D3',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D4',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D5',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D6',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D7',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D8',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D9',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D10', 'SPI',   'SPI SS',                                             cSPI),
    PinRow('D11', 'SPI',   'SPI MOSI',                                           cSPI),
    PinRow('D12', 'SPI',   'SPI MISO',                                           cSPI),
    PinRow('D13', 'Special','SPI SCK · LED',                                    cSpecial),
    PinRow('A0',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A1',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A2',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A3',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A4',  'I2C',   'I2C SDA · 12-bit ADC',                             cI2C),
    PinRow('A5',  'I2C',   'I2C SCL · 12-bit ADC',                             cI2C),
    PinRow('A6',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A7',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('3V3', 'Power', '3.3 V (nRF52840 — BLE 5.0)',                       cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
  ],

  // ══ ARDUINO NANO ESP32 ════════════════════════════════════════════════════
  'Nano ESP32': [
    PinRow('D0',  'UART',  'RX (UART0)',                                         cUART),
    PinRow('D1',  'UART',  'TX (UART0)',                                         cUART),
    PinRow('D2',  'Digital','GPIO — 3.3 V logic',                               cDigital),
    PinRow('D3',  'PWM',   'GPIO · PWM',                                         cPWM),
    PinRow('D4',  'Digital','GPIO',                                              cDigital),
    PinRow('D5',  'PWM',   'GPIO · PWM',                                         cPWM),
    PinRow('D6',  'PWM',   'GPIO · PWM',                                         cPWM),
    PinRow('D7',  'Digital','GPIO',                                              cDigital),
    PinRow('D8',  'Digital','GPIO',                                              cDigital),
    PinRow('D9',  'PWM',   'GPIO · PWM',                                         cPWM),
    PinRow('D10', 'SPI',   'SPI SS',                                             cSPI),
    PinRow('D11', 'SPI',   'SPI MOSI',                                           cSPI),
    PinRow('D12', 'SPI',   'SPI MISO',                                           cSPI),
    PinRow('D13', 'Special','SPI SCK · RGB LED',                                cSpecial),
    PinRow('A0',  'Analog','12-bit ADC · DAC',                                  cAnalog),
    PinRow('A1',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A2',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A3',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A4',  'I2C',   'I2C SDA · ADC',                                     cI2C),
    PinRow('A5',  'I2C',   'I2C SCL · ADC',                                     cI2C),
    PinRow('A6',  'Analog','ADC',                                                cAnalog),
    PinRow('A7',  'Analog','ADC',                                                cAnalog),
    PinRow('3V3', 'Power', '3.3 V (ESP32-S3 based)',                            cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
  ],

  // ══ ARDUINO DUE (SAM3X8E — 3.3 V only!) ══════════════════════════════════
  'Due': [
    PinRow('D0',  'UART',  'RX0 — ⚠ 3.3 V only!',                             cUART),
    PinRow('D1',  'UART',  'TX0',                                                cUART),
    PinRow('D2',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D3',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D13', 'Special','SPI SCK · LED',                                    cSpecial),
    PinRow('D18', 'UART',  'TX1',                                                cUART),
    PinRow('D19', 'UART',  'RX1',                                                cUART),
    PinRow('D20', 'I2C',   'SDA1 (Wire1)',                                       cI2C),
    PinRow('D21', 'I2C',   'SCL1 (Wire1)',                                       cI2C),
    PinRow('D50', 'SPI',   'SPI MISO',                                           cSPI),
    PinRow('D51', 'SPI',   'SPI MOSI',                                           cSPI),
    PinRow('D52', 'SPI',   'SPI SCK',                                            cSPI),
    PinRow('D53', 'SPI',   'SPI SS',                                             cSPI),
    PinRow('SDA', 'I2C',   'I2C SDA (Wire)',                                     cI2C),
    PinRow('SCL', 'I2C',   'I2C SCL (Wire)',                                     cI2C),
    PinRow('A0',  'Analog','12-bit ADC · DAC0',                                 cAnalog),
    PinRow('A1',  'Analog','12-bit ADC · DAC1',                                 cAnalog),
    PinRow('A2',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A3',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A4',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A5',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A6–A11','Analog','12-bit ADC (additional)',                         cAnalog),
    PinRow('3.3V','Power', '3.3 V (⚠ all I/O is 3.3 V)',                      cPower),
    PinRow('5V',  'Power', '5 V output',                                        cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
  ],

  // ══ ARDUINO LEONARDO / MICRO ══════════════════════════════════════════════
  'Leonardo': [
    PinRow('D0',  'UART',  'RX (Serial1 — hardware UART)',                      cUART),
    PinRow('D1',  'UART',  'TX (Serial1)',                                       cUART),
    PinRow('D2',  'Special','SDA · Digital · Interrupt 1',                      cI2C),
    PinRow('D3',  'Special','SCL · Digital · PWM · Interrupt 0',                cI2C),
    PinRow('D4',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D5',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D6',  'PWM',   'Digital · PWM · A7',                                cPWM),
    PinRow('D7',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D8',  'Analog','Digital · A8',                                      cDigital),
    PinRow('D9',  'PWM',   'Digital · PWM · A9',                                cPWM),
    PinRow('D10', 'PWM',   'Digital · PWM · SPI SS · A10',                     cPWM),
    PinRow('D11', 'SPI',   'Digital · PWM · SPI MOSI',                         cSPI),
    PinRow('D12', 'SPI',   'Digital · SPI MISO · A11',                         cSPI),
    PinRow('D13', 'Special','Digital · SPI SCK · LED',                          cSpecial),
    PinRow('A0',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('A1',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('A2',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('A3',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('A4',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('A5',  'Analog','Analog 10-bit',                                     cAnalog),
    PinRow('5V',  'Power', '5 V (USB powered)',                                 cPower),
    PinRow('3.3V','Power', '3.3 V output',                                      cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
  ],

  // ══ ARDUINO PRO MINI ══════════════════════════════════════════════════════
  'Pro Mini 3.3V': [
    PinRow('D0',  'UART',  'RX',                                                 cUART),
    PinRow('D1',  'UART',  'TX',                                                 cUART),
    PinRow('D2',  'Digital','Digital · Interrupt',                              cDigital),
    PinRow('D3',  'PWM',   'Digital · PWM · Interrupt',                         cPWM),
    PinRow('D4',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D5',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D6',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D7',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D8',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D9',  'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D10', 'SPI',   'SPI SS · PWM',                                      cSPI),
    PinRow('D11', 'SPI',   'SPI MOSI · PWM',                                    cSPI),
    PinRow('D12', 'SPI',   'SPI MISO',                                           cSPI),
    PinRow('D13', 'Special','SPI SCK · LED',                                    cSpecial),
    PinRow('A0',  'Analog','10-bit ADC',                                        cAnalog),
    PinRow('A1',  'Analog','10-bit ADC',                                        cAnalog),
    PinRow('A2',  'Analog','10-bit ADC',                                        cAnalog),
    PinRow('A3',  'Analog','10-bit ADC',                                        cAnalog),
    PinRow('A4',  'I2C',   'I2C SDA · ADC',                                     cI2C),
    PinRow('A5',  'I2C',   'I2C SCL · ADC',                                     cI2C),
    PinRow('A6',  'Analog','ADC only',                                          cAnalog),
    PinRow('A7',  'Analog','ADC only',                                          cAnalog),
    PinRow('VCC', 'Power', '3.3 V regulated (8 MHz variant)',                  cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
    PinRow('RAW', 'Power', 'Unregulated input (3.35–12 V)',                    cPower),
  ],

  // ══ ARDUINO MKR WiFi 1010 ═════════════════════════════════════════════════
  'MKR WiFi 1010': [
    PinRow('D0',  'Digital','Digital I/O — 3.3 V logic',                       cDigital),
    PinRow('D1',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D2',  'SPI',   'SPI MOSI',                                           cSPI),
    PinRow('D3',  'SPI',   'SPI SCK',                                            cSPI),
    PinRow('D4',  'SPI',   'SPI MISO',                                           cSPI),
    PinRow('D5',  'SPI',   'SPI SS',                                             cSPI),
    PinRow('D6',  'Digital','Digital I/O',                                      cDigital),
    PinRow('D7',  'I2C',   'I2C SDA',                                            cI2C),
    PinRow('D8',  'I2C',   'I2C SCL',                                            cI2C),
    PinRow('D9',  'UART',  'UART RX (Serial1)',                                  cUART),
    PinRow('D10', 'UART',  'UART TX (Serial1)',                                  cUART),
    PinRow('D11', 'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D12', 'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D13', 'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('D14', 'PWM',   'Digital · PWM',                                     cPWM),
    PinRow('A0',  'Analog','12-bit ADC · DAC',                                  cAnalog),
    PinRow('A1',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A2',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A3',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A4',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A5',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('A6',  'Analog','12-bit ADC',                                        cAnalog),
    PinRow('3V3', 'Power', '3.3 V output',                                      cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
    PinRow('VIN', 'Power', '5 V input',                                         cPower),
  ],

  // ══ ARDUINO PORTENTA H7 (STM32H747) ══════════════════════════════════════
  'Portenta H7': [
    PinRow('D0',  'UART',  'RX (Serial1)',                                       cUART),
    PinRow('D1',  'UART',  'TX (Serial1)',                                       cUART),
    PinRow('D2–D21','PWM', 'Digital I/O · PWM capable (3.3 V logic)',           cPWM),
    PinRow('A0',  'Analog','16-bit ADC',                                        cAnalog),
    PinRow('A1',  'Analog','16-bit ADC',                                        cAnalog),
    PinRow('A2',  'Analog','16-bit ADC',                                        cAnalog),
    PinRow('A3',  'Analog','16-bit ADC',                                        cAnalog),
    PinRow('A4',  'Analog','16-bit ADC',                                        cAnalog),
    PinRow('A5',  'Analog','16-bit ADC',                                        cAnalog),
    PinRow('A6',  'Analog','16-bit ADC',                                        cAnalog),
    PinRow('SDA', 'I2C',   'I2C SDA (Wire)',                                     cI2C),
    PinRow('SCL', 'I2C',   'I2C SCL (Wire)',                                     cI2C),
    PinRow('MOSI','SPI',   'SPI MOSI',                                           cSPI),
    PinRow('MISO','SPI',   'SPI MISO',                                           cSPI),
    PinRow('SCK', 'SPI',   'SPI SCK',                                            cSPI),
    PinRow('3V3', 'Power', '3.3 V output',                                      cPower),
    PinRow('GND', 'GND',   'Ground',                                             cGND),
  ],

  // ══ RASPBERRY PI 40-pin header (Pi 1B+ through Pi 5) ═════════════════════
  'Pi 40-pin': [
    PinRow('GPIO 2',  'I2C',   'I2C1 SDA',                                       cI2C),
    PinRow('GPIO 3',  'I2C',   'I2C1 SCL',                                       cI2C),
    PinRow('GPIO 4',  'Digital','GPCLK0 · 1-Wire',                              cDigital),
    PinRow('GPIO 5',  'Digital','Digital I/O',                                  cDigital),
    PinRow('GPIO 6',  'Digital','Digital I/O',                                  cDigital),
    PinRow('GPIO 7',  'SPI',   'SPI0 CE1',                                       cSPI),
    PinRow('GPIO 8',  'SPI',   'SPI0 CE0',                                       cSPI),
    PinRow('GPIO 9',  'SPI',   'SPI0 MISO',                                      cSPI),
    PinRow('GPIO 10', 'SPI',   'SPI0 MOSI',                                      cSPI),
    PinRow('GPIO 11', 'SPI',   'SPI0 SCLK',                                      cSPI),
    PinRow('GPIO 12', 'PWM',   'PWM0',                                           cPWM),
    PinRow('GPIO 13', 'PWM',   'PWM1',                                           cPWM),
    PinRow('GPIO 14', 'UART',  'UART TX (TXD0)',                                 cUART),
    PinRow('GPIO 15', 'UART',  'UART RX (RXD0)',                                 cUART),
    PinRow('GPIO 16', 'SPI',   'SPI1 CE2',                                       cSPI),
    PinRow('GPIO 17', 'Digital','Digital I/O',                                  cDigital),
    PinRow('GPIO 18', 'PWM',   'PCM CLK · PWM0 · SPI1 CE0',                    cPWM),
    PinRow('GPIO 19', 'SPI',   'SPI1 MISO · PWM1',                              cSPI),
    PinRow('GPIO 20', 'SPI',   'SPI1 MOSI · GPCLK0',                           cSPI),
    PinRow('GPIO 21', 'SPI',   'SPI1 SCLK',                                     cSPI),
    PinRow('GPIO 22', 'Digital','Digital I/O',                                  cDigital),
    PinRow('GPIO 23', 'Digital','Digital I/O',                                  cDigital),
    PinRow('GPIO 24', 'Digital','Digital I/O',                                  cDigital),
    PinRow('GPIO 25', 'Digital','Digital I/O',                                  cDigital),
    PinRow('GPIO 26', 'Digital','Digital I/O',                                  cDigital),
    PinRow('GPIO 27', 'Digital','Digital I/O',                                  cDigital),
    PinRow('3V3',     'Power', '3.3 V — 50 mA max per pin (Pi 4/5: 500 mA total)',cPower),
    PinRow('5V',      'Power', '5 V from power input',                          cPower),
    PinRow('GND',     'GND',   'Ground',                                         cGND),
    PinRow('ID_SD',   'Special','HAT ID EEPROM SDA',                            cSpecial),
    PinRow('ID_SC',   'Special','HAT ID EEPROM SCL',                            cSpecial),
  ],

  // ══ RASPBERRY PI PICO (RP2040) ════════════════════════════════════════════
  'Pico': [
    PinRow('GP0',  'UART','UART0 TX · SPI0 RX · I2C0 SDA · PWM0A',             cUART),
    PinRow('GP1',  'UART','UART0 RX · SPI0 CSn · I2C0 SCL · PWM0B',            cUART),
    PinRow('GP2',  'SPI', 'SPI0 SCK · I2C1 SDA · PWM1A',                       cSPI),
    PinRow('GP3',  'SPI', 'SPI0 TX · I2C1 SCL · PWM1B',                        cSPI),
    PinRow('GP4',  'I2C', 'UART1 TX · SPI0 RX · I2C0 SDA · PWM2A',            cI2C),
    PinRow('GP5',  'I2C', 'UART1 RX · SPI0 CSn · I2C0 SCL · PWM2B',           cI2C),
    PinRow('GP6',  'Digital','I2C1 SDA · PWM3A',                                cDigital),
    PinRow('GP7',  'Digital','I2C1 SCL · PWM3B',                                cDigital),
    PinRow('GP8',  'UART','UART1 TX · SPI1 RX · I2C0 SDA · PWM4A',             cUART),
    PinRow('GP9',  'UART','UART1 RX · SPI1 CSn · I2C0 SCL · PWM4B',            cUART),
    PinRow('GP10', 'SPI', 'SPI1 SCK · I2C1 SDA · PWM5A',                       cSPI),
    PinRow('GP11', 'SPI', 'SPI1 TX · I2C1 SCL · PWM5B',                        cSPI),
    PinRow('GP12', 'SPI', 'SPI1 RX · I2C0 SDA · PWM6A',                        cSPI),
    PinRow('GP13', 'SPI', 'SPI1 CSn · I2C0 SCL · PWM6B',                       cSPI),
    PinRow('GP14', 'Digital','SPI1 SCK (alt) · I2C1 SDA · PWM7A',              cDigital),
    PinRow('GP15', 'Digital','I2C1 SCL · PWM7B',                                cDigital),
    PinRow('GP16', 'SPI', 'SPI0 RX · I2C0 SDA · PWM0A',                        cSPI),
    PinRow('GP17', 'SPI', 'SPI0 CSn · I2C0 SCL · PWM0B',                       cSPI),
    PinRow('GP18', 'SPI', 'SPI0 SCK · I2C1 SDA · PWM1A',                       cSPI),
    PinRow('GP19', 'SPI', 'SPI0 TX · I2C1 SCL · PWM1B',                        cSPI),
    PinRow('GP20', 'Digital','I2C0 SDA · PWM2A',                                cDigital),
    PinRow('GP21', 'Digital','I2C0 SCL · PWM2B',                                cDigital),
    PinRow('GP22', 'Digital','PWM3A',                                            cDigital),
    PinRow('GP25', 'Special','Built-in LED (Pico) / WiFi LED (Pico W)',         cSpecial),
    PinRow('GP26', 'Analog','ADC0 · I2C1 SDA · PWM5A',                         cAnalog),
    PinRow('GP27', 'Analog','ADC1 · I2C1 SCL · PWM5B',                         cAnalog),
    PinRow('GP28', 'Analog','ADC2 · I2C0 SDA · PWM6A',                         cAnalog),
    PinRow('ADC_VREF','Special','ADC reference voltage',                        cSpecial),
    PinRow('3V3',  'Power','3.3 V output (300 mA max)',                         cPower),
    PinRow('3V3_EN','Special','Pull LOW to disable 3V3 regulator',              cSpecial),
    PinRow('VSYS', 'Power','2–5 V input (USB or battery)',                      cPower),
    PinRow('VBUS', 'Power','5 V from USB connector',                            cPower),
    PinRow('GND',  'GND',  'Ground',                                             cGND),
    PinRow('RUN',  'Special','Reset pin (active LOW)',                           cSpecial),
  ],

  // ══ RASPBERRY PI PICO 2 (RP2350) ══════════════════════════════════════════
  'Pico 2W': [
    PinRow('GP0',  'UART','UART0 TX · SPI0 RX · I2C0 SDA · PWM0A',             cUART),
    PinRow('GP1',  'UART','UART0 RX · SPI0 CSn · I2C0 SCL · PWM0B',            cUART),
    PinRow('GP2',  'SPI', 'SPI0 SCK · I2C1 SDA · PWM1A',                       cSPI),
    PinRow('GP3',  'SPI', 'SPI0 TX · I2C1 SCL · PWM1B',                        cSPI),
    PinRow('GP4',  'I2C', 'UART1 TX · I2C0 SDA · PWM2A',                       cI2C),
    PinRow('GP5',  'I2C', 'UART1 RX · I2C0 SCL · PWM2B',                       cI2C),
    PinRow('GP6',  'Digital','PWM3A',                                            cDigital),
    PinRow('GP7',  'Digital','PWM3B',                                            cDigital),
    PinRow('GP8',  'UART','UART1 TX · PWM4A',                                   cUART),
    PinRow('GP9',  'UART','UART1 RX · PWM4B',                                   cUART),
    PinRow('GP10', 'SPI', 'SPI1 SCK · PWM5A',                                   cSPI),
    PinRow('GP11', 'SPI', 'SPI1 TX · PWM5B',                                    cSPI),
    PinRow('GP12', 'SPI', 'SPI1 RX · PWM6A',                                    cSPI),
    PinRow('GP13', 'SPI', 'SPI1 CSn · PWM6B',                                   cSPI),
    PinRow('GP14', 'Digital','PWM7A',                                            cDigital),
    PinRow('GP15', 'Digital','PWM7B',                                            cDigital),
    PinRow('GP25', 'Special','WiFi/BT LED (2W) or built-in LED',                cSpecial),
    PinRow('GP26', 'Analog','ADC0',                                              cAnalog),
    PinRow('GP27', 'Analog','ADC1',                                              cAnalog),
    PinRow('GP28', 'Analog','ADC2',                                              cAnalog),
    PinRow('3V3',  'Power','3.3 V output (RP2350 — dual Cortex-M33 / RISC-V)', cPower),
    PinRow('VSYS', 'Power','2–5 V input',                                       cPower),
    PinRow('GND',  'GND',  'Ground',                                             cGND),
  ],

  // ══ STM32 BLUE PILL (F103C8T6) ════════════════════════════════════════════
  'Blue Pill (F103C8)': [
    PinRow('PA0',  'Analog','ADC12_IN0 · WKUP · TIM2_CH1',                     cAnalog),
    PinRow('PA1',  'Analog','ADC12_IN1 · TIM2_CH2',                             cAnalog),
    PinRow('PA2',  'UART',  'USART2_TX · ADC12_IN2 · TIM2_CH3',               cUART),
    PinRow('PA3',  'UART',  'USART2_RX · ADC12_IN3 · TIM2_CH4',               cUART),
    PinRow('PA4',  'SPI',   'SPI1_NSS · ADC12_IN4 · DAC_OUT1',                 cSPI),
    PinRow('PA5',  'SPI',   'SPI1_SCK · ADC12_IN5 · DAC_OUT2',                 cSPI),
    PinRow('PA6',  'SPI',   'SPI1_MISO · ADC12_IN6 · TIM3_CH1',               cSPI),
    PinRow('PA7',  'SPI',   'SPI1_MOSI · ADC12_IN7 · TIM3_CH2',               cSPI),
    PinRow('PA8',  'Digital','TIM1_CH1 · MCO · USART1_CK',                     cDigital),
    PinRow('PA9',  'UART',  'USART1_TX · TIM1_CH2',                             cUART),
    PinRow('PA10', 'UART',  'USART1_RX · TIM1_CH3',                             cUART),
    PinRow('PA11', 'Special','USB_DM · CAN_RX · TIM1_CH4',                     cSpecial),
    PinRow('PA12', 'Special','USB_DP · CAN_TX',                                  cSpecial),
    PinRow('PA13', 'Special','JTMS / SWDIO',                                    cSpecial),
    PinRow('PA14', 'Special','JTCK / SWCLK',                                    cSpecial),
    PinRow('PA15', 'Digital','JTDI · TIM2_CH1_ETR · SPI1_NSS',                 cDigital),
    PinRow('PB0',  'Analog','ADC12_IN8 · TIM3_CH3',                             cAnalog),
    PinRow('PB1',  'Analog','ADC12_IN9 · TIM3_CH4',                             cAnalog),
    PinRow('PB3',  'Special','JTDO · TIM2_CH2 · SPI1_SCK',                     cSpecial),
    PinRow('PB4',  'Special','NJTRST · TIM3_CH1 · SPI1_MISO',                  cSpecial),
    PinRow('PB5',  'I2C',   'I2C1_SMBA · TIM3_CH2 · SPI1_MOSI',              cI2C),
    PinRow('PB6',  'I2C',   'I2C1_SCL · TIM4_CH1 · USART1_TX',               cI2C),
    PinRow('PB7',  'I2C',   'I2C1_SDA · TIM4_CH2 · USART1_RX',               cI2C),
    PinRow('PB8',  'I2C',   'I2C1_SCL (remap) · TIM4_CH3 · CAN_RX',          cI2C),
    PinRow('PB9',  'I2C',   'I2C1_SDA (remap) · TIM4_CH4 · CAN_TX',          cI2C),
    PinRow('PB10', 'I2C',   'I2C2_SCL · USART3_TX · TIM2_CH3',               cI2C),
    PinRow('PB11', 'I2C',   'I2C2_SDA · USART3_RX · TIM2_CH4',               cI2C),
    PinRow('PB12', 'SPI',   'SPI2_NSS · I2C2_SMBA · USART3_CK',              cSPI),
    PinRow('PB13', 'SPI',   'SPI2_SCK · USART3_CTS',                           cSPI),
    PinRow('PB14', 'SPI',   'SPI2_MISO · USART3_RTS',                          cSPI),
    PinRow('PB15', 'SPI',   'SPI2_MOSI',                                        cSPI),
    PinRow('PC13', 'Special','Built-in LED (active LOW) · RTC output',          cSpecial),
    PinRow('PC14', 'Special','OSC32_IN (32 kHz crystal)',                       cSpecial),
    PinRow('PC15', 'Special','OSC32_OUT',                                        cSpecial),
    PinRow('3V3',  'Power', '3.3 V regulated output',                           cPower),
    PinRow('GND',  'GND',   'Ground',                                            cGND),
  ],

  // ══ STM32 BLACK PILL F401 (WeAct / F401CCU6) ══════════════════════════════
  'Black Pill (F401)': [
    PinRow('PA0',  'Analog','ADC1_IN0 · TIM2_CH1 · TIM5_CH1',                  cAnalog),
    PinRow('PA1',  'Analog','ADC1_IN1 · TIM2_CH2 · TIM5_CH2',                  cAnalog),
    PinRow('PA2',  'UART',  'USART2_TX · ADC1_IN2 · TIM2_CH3',                cUART),
    PinRow('PA3',  'UART',  'USART2_RX · ADC1_IN3 · TIM2_CH4',                cUART),
    PinRow('PA4',  'SPI',   'SPI1_NSS · ADC1_IN4 · TIM3_CH2',                 cSPI),
    PinRow('PA5',  'SPI',   'SPI1_SCK · ADC1_IN5 · TIM2_CH1',                 cSPI),
    PinRow('PA6',  'SPI',   'SPI1_MISO · ADC1_IN6 · TIM3_CH1',               cSPI),
    PinRow('PA7',  'SPI',   'SPI1_MOSI · ADC1_IN7 · TIM3_CH2',               cSPI),
    PinRow('PA8',  'Digital','TIM1_CH1 · MCO',                                  cDigital),
    PinRow('PA9',  'UART',  'USART1_TX · TIM1_CH2',                             cUART),
    PinRow('PA10', 'UART',  'USART1_RX · TIM1_CH3',                             cUART),
    PinRow('PA11', 'Special','USB_DM',                                           cSpecial),
    PinRow('PA12', 'Special','USB_DP',                                           cSpecial),
    PinRow('PA13', 'Special','SWDIO',                                            cSpecial),
    PinRow('PA14', 'Special','SWCLK',                                            cSpecial),
    PinRow('PA15', 'Digital','SPI1_NSS (remap) · TIM2_CH1',                    cDigital),
    PinRow('PB0',  'Analog','ADC1_IN8 · TIM3_CH3',                              cAnalog),
    PinRow('PB1',  'Analog','ADC1_IN9 · TIM3_CH4',                              cAnalog),
    PinRow('PB3',  'SPI',   'SPI1_SCK (remap) · TIM2_CH2',                    cSPI),
    PinRow('PB4',  'SPI',   'SPI1_MISO (remap) · TIM3_CH1',                   cSPI),
    PinRow('PB5',  'SPI',   'SPI1_MOSI (remap) · TIM3_CH2',                   cSPI),
    PinRow('PB6',  'I2C',   'I2C1_SCL · USART1_TX · TIM4_CH1',               cI2C),
    PinRow('PB7',  'I2C',   'I2C1_SDA · USART1_RX · TIM4_CH2',               cI2C),
    PinRow('PB8',  'I2C',   'I2C1_SCL (remap) · TIM4_CH3 · CAN1_RX',         cI2C),
    PinRow('PB9',  'I2C',   'I2C1_SDA (remap) · TIM4_CH4 · CAN1_TX',         cI2C),
    PinRow('PB10', 'I2C',   'I2C2_SCL · USART3_TX',                            cI2C),
    PinRow('PB12', 'SPI',   'SPI2_NSS · I2C2_SMBA',                            cSPI),
    PinRow('PB13', 'SPI',   'SPI2_SCK',                                          cSPI),
    PinRow('PB14', 'SPI',   'SPI2_MISO',                                         cSPI),
    PinRow('PB15', 'SPI',   'SPI2_MOSI',                                         cSPI),
    PinRow('PC13', 'Special','Built-in LED (active LOW)',                        cSpecial),
    PinRow('3V3',  'Power', '3.3 V output',                                     cPower),
    PinRow('GND',  'GND',   'Ground',                                            cGND),
  ],

  // ══ STM32 BLACK PILL F411 ═════════════════════════════════════════════════
  'Black Pill (F411)': [
    PinRow('PA0',  'Analog','ADC1_IN0 · TIM2_CH1 · TIM5_CH1',                  cAnalog),
    PinRow('PA1',  'Analog','ADC1_IN1 · TIM2_CH2 · TIM5_CH2',                  cAnalog),
    PinRow('PA2',  'UART',  'USART2_TX · ADC1_IN2',                             cUART),
    PinRow('PA3',  'UART',  'USART2_RX · ADC1_IN3',                             cUART),
    PinRow('PA4',  'SPI',   'SPI1_NSS · ADC1_IN4 · I2S3_WS',                  cSPI),
    PinRow('PA5',  'SPI',   'SPI1_SCK · ADC1_IN5 · I2S3_BCK',                 cSPI),
    PinRow('PA6',  'SPI',   'SPI1_MISO · ADC1_IN6 · TIM3_CH1',               cSPI),
    PinRow('PA7',  'SPI',   'SPI1_MOSI · ADC1_IN7 · TIM3_CH2',               cSPI),
    PinRow('PA9',  'UART',  'USART1_TX · TIM1_CH2',                             cUART),
    PinRow('PA10', 'UART',  'USART1_RX · TIM1_CH3',                             cUART),
    PinRow('PA11', 'Special','USB_DM · CAN1_RX',                                cSpecial),
    PinRow('PA12', 'Special','USB_DP · CAN1_TX',                                cSpecial),
    PinRow('PA13', 'Special','SWDIO',                                            cSpecial),
    PinRow('PA14', 'Special','SWCLK',                                            cSpecial),
    PinRow('PB3',  'SPI',   'SPI1_SCK (alt) · I2S3_BCK · TIM2_CH2',          cSPI),
    PinRow('PB4',  'SPI',   'SPI1_MISO (alt) · I2S3_SD · TIM3_CH1',          cSPI),
    PinRow('PB5',  'SPI',   'SPI1_MOSI (alt) · TIM3_CH2',                     cSPI),
    PinRow('PB6',  'I2C',   'I2C1_SCL · USART1_TX',                            cI2C),
    PinRow('PB7',  'I2C',   'I2C1_SDA · USART1_RX',                            cI2C),
    PinRow('PB8',  'I2C',   'I2C1_SCL (remap) · TIM4_CH3 · CAN1_RX',         cI2C),
    PinRow('PB9',  'I2C',   'I2C1_SDA (remap) · TIM4_CH4 · CAN1_TX',         cI2C),
    PinRow('PB10', 'I2C',   'I2C2_SCL · USART3_TX · SPI2_SCK',               cI2C),
    PinRow('PB12', 'SPI',   'SPI2_NSS · SPI1_NSS (remap)',                    cSPI),
    PinRow('PB13', 'SPI',   'SPI2_SCK',                                          cSPI),
    PinRow('PB14', 'SPI',   'SPI2_MISO',                                         cSPI),
    PinRow('PB15', 'SPI',   'SPI2_MOSI',                                         cSPI),
    PinRow('PC13', 'Special','Built-in LED (active LOW)',                        cSpecial),
    PinRow('3V3',  'Power', '3.3 V output',                                     cPower),
    PinRow('GND',  'GND',   'Ground',                                            cGND),
  ],

  // ══ STM32 NUCLEO-64 (F103RB / F401RE / F411RE / F446RE) ══════════════════
  'Nucleo-64': [
    PinRow('PA0',  'Analog','ADC_IN0 · WKUP · TIM2/5_CH1',                     cAnalog),
    PinRow('PA1',  'Analog','ADC_IN1 · TIM2/5_CH2',                             cAnalog),
    PinRow('PA2',  'UART',  'USART2_TX (ST-Link VCP) · ADC_IN2',              cUART),
    PinRow('PA3',  'UART',  'USART2_RX (ST-Link VCP) · ADC_IN3',              cUART),
    PinRow('PA4',  'SPI',   'SPI1_NSS · ADC_IN4 · DAC1',                       cSPI),
    PinRow('PA5',  'SPI',   'SPI1_SCK · ADC_IN5 · LD2 (User LED)',             cSPI),
    PinRow('PA6',  'SPI',   'SPI1_MISO · ADC_IN6 · TIM3_CH1',                 cSPI),
    PinRow('PA7',  'SPI',   'SPI1_MOSI · ADC_IN7 · TIM3_CH2',                 cSPI),
    PinRow('PA9',  'UART',  'USART1_TX · TIM1_CH2',                             cUART),
    PinRow('PA10', 'UART',  'USART1_RX · TIM1_CH3',                             cUART),
    PinRow('PB3',  'SPI',   'SPI1/3_SCK (alt) · TIM2_CH2',                    cSPI),
    PinRow('PB4',  'SPI',   'SPI1/3_MISO (alt) · TIM3_CH1',                   cSPI),
    PinRow('PB5',  'SPI',   'SPI1/3_MOSI (alt) · TIM3_CH2',                   cSPI),
    PinRow('PB6',  'I2C',   'I2C1_SCL · USART1_TX · TIM4_CH1',               cI2C),
    PinRow('PB7',  'I2C',   'I2C1_SDA · USART1_RX · TIM4_CH2',               cI2C),
    PinRow('PB8',  'I2C',   'I2C1_SCL (remap) · CAN1_RX · TIM4_CH3',         cI2C),
    PinRow('PB9',  'I2C',   'I2C1_SDA (remap) · CAN1_TX · TIM4_CH4',         cI2C),
    PinRow('PB10', 'I2C',   'I2C2_SCL · USART3_TX',                            cI2C),
    PinRow('PB13', 'SPI',   'SPI2_SCK',                                          cSPI),
    PinRow('PB14', 'SPI',   'SPI2_MISO',                                         cSPI),
    PinRow('PB15', 'SPI',   'SPI2_MOSI',                                         cSPI),
    PinRow('PC13', 'Special','B1 User Button (active LOW)',                      cSpecial),
    PinRow('3V3',  'Power', '3.3 V from ST-Link or external',                  cPower),
    PinRow('5V',   'Power', '5 V from USB',                                     cPower),
    PinRow('GND',  'GND',   'Ground',                                            cGND),
  ],

  // ══ STM32 NUCLEO-144 (F767ZI / H743ZI) ═══════════════════════════════════
  'Nucleo-144': [
    PinRow('PA0',  'Analog','ADC_IN0 · WKUP · TIM2_CH1',                       cAnalog),
    PinRow('PA2',  'UART',  'USART2_TX',                                         cUART),
    PinRow('PA3',  'UART',  'USART2_RX',                                         cUART),
    PinRow('PA5',  'SPI',   'SPI1_SCK · LED LD1 (Green)',                       cSPI),
    PinRow('PB0',  'Special','LED LD3 (Blue)',                                   cSpecial),
    PinRow('PB7',  'Special','LED LD2 (Blue)',                                   cSpecial),
    PinRow('PB8',  'I2C',   'I2C1_SCL',                                          cI2C),
    PinRow('PB9',  'I2C',   'I2C1_SDA',                                          cI2C),
    PinRow('PB14', 'Special','LED LD3 (Red)',                                    cSpecial),
    PinRow('PC13', 'Special','B1 User Button (active LOW)',                      cSpecial),
    PinRow('PD8',  'UART',  'USART3_TX (ST-Link VCP)',                          cUART),
    PinRow('PD9',  'UART',  'USART3_RX (ST-Link VCP)',                          cUART),
    PinRow('ZIO CN7/CN10','Digital','Arduino-compatible header D0–D15',         cDigital),
    PinRow('Morpho CN11/CN12','Digital','STM-specific 144-pin expansion',       cDigital),
    PinRow('3V3',  'Power', '3.3 V',                                             cPower),
    PinRow('5V',   'Power', '5 V from USB',                                     cPower),
    PinRow('GND',  'GND',   'Ground',                                            cGND),
  ],

  // ══ STM32F4-DISCOVERY ═════════════════════════════════════════════════════
  'STM32F4-Discovery': [
    PinRow('PA0',  'Special','USER Button B1 · WKUP · ADC1_IN0',               cSpecial),
    PinRow('PA1',  'Analog','ADC1_IN1',                                          cAnalog),
    PinRow('PA2',  'UART',  'USART2_TX · ADC1_IN2',                             cUART),
    PinRow('PA3',  'UART',  'USART2_RX · ADC1_IN3',                             cUART),
    PinRow('PA4',  'SPI',   'SPI1_NSS · ADC1_IN4 · DAC_OUT1',                  cSPI),
    PinRow('PA5',  'SPI',   'SPI1_SCK · ADC1_IN5 · DAC_OUT2',                  cSPI),
    PinRow('PA6',  'SPI',   'SPI1_MISO · ADC1_IN6',                             cSPI),
    PinRow('PA7',  'SPI',   'SPI1_MOSI · ADC1_IN7',                             cSPI),
    PinRow('PB6',  'I2C',   'I2C1_SCL',                                          cI2C),
    PinRow('PB7',  'I2C',   'I2C1_SDA',                                          cI2C),
    PinRow('PD4',  'Special','CS43L22 Reset',                                    cSpecial),
    PinRow('PD12', 'Special','LD4 Green LED',                                    cSpecial),
    PinRow('PD13', 'Special','LD3 Orange LED',                                   cSpecial),
    PinRow('PD14', 'Special','LD5 Red LED',                                      cSpecial),
    PinRow('PD15', 'Special','LD6 Blue LED',                                     cSpecial),
    PinRow('PE3',  'Special','MEMS CS (LIS302DL)',                               cSpecial),
    PinRow('3V3',  'Power', '3.3 V output',                                     cPower),
    PinRow('5V',   'Power', '5 V from USB',                                     cPower),
    PinRow('GND',  'GND',   'Ground',                                            cGND),
  ],

  // ══ STM32 Nucleo-WB55 (BLE) ═══════════════════════════════════════════════
  'Nucleo-WB55 (BLE)': [
    PinRow('PA0',  'Analog','ADC1_IN5 · TIM2_CH1',                              cAnalog),
    PinRow('PA1',  'Analog','ADC1_IN6 · TIM2_CH2',                              cAnalog),
    PinRow('PA2',  'UART',  'LPUART1_TX · ADC1_IN7',                            cUART),
    PinRow('PA3',  'UART',  'LPUART1_RX · ADC1_IN8',                            cUART),
    PinRow('PA4',  'SPI',   'SPI1_NSS · ADC1_IN9',                              cSPI),
    PinRow('PA5',  'SPI',   'SPI1_SCK · ADC1_IN10 · LD2 LED',                 cSPI),
    PinRow('PA6',  'SPI',   'SPI1_MISO · ADC1_IN11',                           cSPI),
    PinRow('PA7',  'SPI',   'SPI1_MOSI · ADC1_IN12',                           cSPI),
    PinRow('PB6',  'I2C',   'I2C1_SCL',                                          cI2C),
    PinRow('PB7',  'I2C',   'I2C1_SDA · LD3 LED',                               cI2C),
    PinRow('PB8',  'I2C',   'I2C1_SCL (remap)',                                  cI2C),
    PinRow('PB9',  'I2C',   'I2C1_SDA (remap)',                                  cI2C),
    PinRow('PC13', 'Special','B1 User Button',                                   cSpecial),
    PinRow('2.4 GHz RF','Special','Integrated BLE 5.0 + IEEE 802.15.4',        cSpecial),
    PinRow('3V3',  'Power', '3.3 V',                                             cPower),
    PinRow('GND',  'GND',   'Ground',                                            cGND),
  ],

  // ══ STM32 Nucleo-WL55 (LoRa) ══════════════════════════════════════════════
  'Nucleo-WL55 (LoRa)': [
    PinRow('PA0',  'Analog','ADC1_IN0',                                          cAnalog),
    PinRow('PA2',  'UART',  'USART2_TX',                                         cUART),
    PinRow('PA3',  'UART',  'USART2_RX',                                         cUART),
    PinRow('PA5',  'SPI',   'SPI1_SCK · LD2 LED',                               cSPI),
    PinRow('PB6',  'I2C',   'I2C1_SCL',                                          cI2C),
    PinRow('PB7',  'I2C',   'I2C1_SDA',                                          cI2C),
    PinRow('PC13', 'Special','B1 User Button',                                   cSpecial),
    PinRow('Sub-GHz RF','Special','Integrated LoRa / FSK / (G)FSK transceiver', cSpecial),
    PinRow('3V3',  'Power', '3.3 V',                                             cPower),
    PinRow('GND',  'GND',   'Ground',                                            cGND),
  ],

  // ══ MAPLE MINI (STM32F103CBT6) ════════════════════════════════════════════
  'Maple Mini': [
    PinRow('D0',  'Digital','PA3 · USART2_RX · ADC_IN3',                       cDigital),
    PinRow('D1',  'Digital','PA4 · SPI1_NSS · ADC_IN4',                        cDigital),
    PinRow('D2',  'PWM',    'PA5 · SPI1_SCK · ADC_IN5',                        cPWM),
    PinRow('D3',  'PWM',    'PA6 · SPI1_MISO · ADC_IN6',                       cPWM),
    PinRow('D4',  'PWM',    'PA7 · SPI1_MOSI · ADC_IN7',                       cPWM),
    PinRow('D5',  'PWM',    'PB0 · ADC_IN8',                                   cPWM),
    PinRow('D6',  'Digital','PB1 · ADC_IN9',                                   cDigital),
    PinRow('D7',  'Digital','PA8 · TIM1_CH1',                                  cDigital),
    PinRow('D8',  'UART',   'PA9 · USART1_TX · TIM1_CH2',                      cUART),
    PinRow('D9',  'UART',   'PA10 · USART1_RX · TIM1_CH3',                     cUART),
    PinRow('D10', 'Digital','PB5 · TIM3_CH2',                                  cDigital),
    PinRow('D11', 'I2C',    'PB6 · I2C1_SCL · TIM4_CH1',                       cI2C),
    PinRow('D12', 'I2C',    'PB7 · I2C1_SDA · TIM4_CH2',                       cI2C),
    PinRow('D13', 'I2C',    'PB8 · I2C1_SCL (remap) · TIM4_CH3',              cI2C),
    PinRow('D14', 'Special','PB10 · I2C2_SCL · USART3_TX',                    cSpecial),
    PinRow('D15', 'Special','PB11 · I2C2_SDA · USART3_RX',                    cSpecial),
    PinRow('D16', 'SPI',    'PB12 · SPI2_NSS',                                  cSPI),
    PinRow('D17', 'SPI',    'PB13 · SPI2_SCK',                                  cSPI),
    PinRow('D18', 'SPI',    'PB14 · SPI2_MISO',                                 cSPI),
    PinRow('D19', 'SPI',    'PB15 · SPI2_MOSI',                                 cSPI),
    PinRow('D20', 'Special','Built-in LED · PA1',                               cSpecial),
    PinRow('D21', 'Analog', 'PA0 · ADC_IN0 · USART2_CTS',                      cAnalog),
    PinRow('3V3', 'Power',  '3.3 V',                                             cPower),
    PinRow('GND', 'GND',    'Ground',                                            cGND),
  ],
};

// ── Components catalogue ───────────────────────────────────────────────────────

const componentCatalogue = <Map<String, dynamic>>[
  {'name': 'DHT11 Temp & Humidity',         'icon': Icons.thermostat_rounded,           'tag': 'Sensor'},
  {'name': 'DHT22 Precision Temp & Humid',  'icon': Icons.device_thermostat_rounded,    'tag': 'Sensor'},
  {'name': 'DS18B20 1-Wire Temp',           'icon': Icons.thermostat_auto_rounded,      'tag': 'Sensor'},
  {'name': 'BMP280 Pressure & Temp',        'icon': Icons.compress_rounded,             'tag': 'Sensor'},
  {'name': 'BME280 Env Sensor',             'icon': Icons.wb_cloudy_rounded,            'tag': 'Sensor'},
  {'name': 'MPU-6050 IMU 6-axis',          'icon': Icons.rotate_90_degrees_ccw_rounded,'tag': 'Sensor'},
  {'name': 'HC-SR04 Ultrasonic',            'icon': Icons.sensors_rounded,              'tag': 'Sensor'},
  {'name': 'PIR Motion Sensor',             'icon': Icons.motion_photos_on_rounded,     'tag': 'Sensor'},
  {'name': 'MQ-2 Gas / Smoke',             'icon': Icons.air_rounded,                  'tag': 'Sensor'},
  {'name': 'MQ-135 Air Quality',           'icon': Icons.cloud_rounded,                'tag': 'Sensor'},
  {'name': 'MQ-7 CO Gas',                  'icon': Icons.masks_rounded,                'tag': 'Sensor'},
  {'name': 'LDR Photo Resistor',           'icon': Icons.wb_sunny_rounded,             'tag': 'Sensor'},
  {'name': 'BH1750 Light Intensity',       'icon': Icons.light_mode_rounded,           'tag': 'Sensor'},
  {'name': 'Soil Moisture Sensor',         'icon': Icons.grass_rounded,                'tag': 'Sensor'},
  {'name': 'Rain Drop Sensor',             'icon': Icons.water_drop_rounded,           'tag': 'Sensor'},
  {'name': 'Turbidity Sensor',             'icon': Icons.opacity_rounded,              'tag': 'Sensor'},
  {'name': 'GPS Neo-6M / Neo-8M',         'icon': Icons.location_on_rounded,          'tag': 'Sensor'},
  {'name': 'Hall Effect Sensor',           'icon': Icons.explore_rounded,              'tag': 'Sensor'},
  {'name': 'IR Obstacle Sensor',           'icon': Icons.visibility_rounded,           'tag': 'Sensor'},
  {'name': 'Sound Sensor KY-037',         'icon': Icons.mic_rounded,                  'tag': 'Sensor'},
  {'name': 'Flame / Fire Sensor',         'icon': Icons.local_fire_department_rounded, 'tag': 'Sensor'},
  {'name': 'MAX30100 Pulse Oximeter',     'icon': Icons.monitor_heart_rounded,         'tag': 'Sensor'},
  {'name': 'Load Cell + HX711',           'icon': Icons.scale_rounded,                 'tag': 'Sensor'},
  {'name': 'Servo Motor SG90',            'icon': Icons.rotate_right_rounded,          'tag': 'Actuator'},
  {'name': 'Servo Motor MG996R',          'icon': Icons.settings_rounded,              'tag': 'Actuator'},
  {'name': 'DC Motor + L298N',            'icon': Icons.electric_bolt_rounded,         'tag': 'Actuator'},
  {'name': 'Stepper + A4988',             'icon': Icons.rotate_90_degrees_ccw_rounded, 'tag': 'Actuator'},
  {'name': 'Relay 5V (Single)',           'icon': Icons.power_rounded,                 'tag': 'Actuator'},
  {'name': 'Relay 4-Channel',             'icon': Icons.device_hub_rounded,            'tag': 'Actuator'},
  {'name': 'Buzzer Active',               'icon': Icons.volume_up_rounded,             'tag': 'Actuator'},
  {'name': 'RGB LED Module',              'icon': Icons.lightbulb_rounded,             'tag': 'Output'},
  {'name': 'LCD 16×2 I2C',               'icon': Icons.display_settings_rounded,      'tag': 'Output'},
  {'name': 'OLED 0.96" SSD1306',         'icon': Icons.monitor_rounded,               'tag': 'Output'},
  {'name': 'TFT 2.4" ILI9341',           'icon': Icons.tablet_rounded,                'tag': 'Output'},
  {'name': 'WS2812B LED Strip',           'icon': Icons.linear_scale_rounded,         'tag': 'Output'},
  {'name': 'ESP8266 WiFi Module',         'icon': Icons.wifi_rounded,                  'tag': 'Module'},
  {'name': 'SIM800L GSM Module',          'icon': Icons.sim_card_rounded,              'tag': 'Module'},
  {'name': 'LoRa SX1278',                'icon': Icons.cell_tower_rounded,             'tag': 'Module'},
  {'name': 'NRF24L01 RF 2.4GHz',        'icon': Icons.radio_rounded,                  'tag': 'Module'},
  {'name': 'SD Card Module',              'icon': Icons.sd_card_rounded,               'tag': 'Module'},
];
